"""Order and position bookkeeping.

Fills are tracked per order from two independent authenticated feeds:

* order updates (cumulative ``filled_base_amount`` / ``filled_quote_amount``)
* account trades (individual fills, de-duplicated by ``trade_id``)

Both are monotonic, so the effective fill of an order is simply the larger of
the two. Applying the same message twice, or the two feeds in either order,
can never double-count exposure.
"""

from __future__ import annotations

import enum
import time
import uuid
from collections.abc import Callable
from dataclasses import dataclass, field

LONG = 1
SHORT = -1

# client_order_index layout (uint48): 8-bit bot tag | 40-bit millisecond sequence.
BOT_TAG = 0xB5
_SEQ_BITS = 40
_SEQ_MASK = (1 << _SEQ_BITS) - 1
_EPOCH_MS = 1_704_067_200_000  # 2024-01-01T00:00:00Z


def is_bot_order(client_order_index: int) -> bool:
    """True if this client order index was generated by this bot."""
    return (client_order_index >> _SEQ_BITS) == BOT_TAG


class ClientOrderIds:
    """Unique, strictly increasing client order indices that survive restarts."""

    def __init__(self, last: int = 0, clock: Callable[[], float] = time.time) -> None:
        self._clock = clock
        self._last_seq = last & _SEQ_MASK if is_bot_order(last) else 0

    def next(self) -> int:
        seq = int(self._clock() * 1000) - _EPOCH_MS
        if seq <= self._last_seq:
            seq = self._last_seq + 1
        self._last_seq = seq
        return (BOT_TAG << _SEQ_BITS) | (seq & _SEQ_MASK)

    @property
    def last(self) -> int:
        return (BOT_TAG << _SEQ_BITS) | self._last_seq if self._last_seq else 0


class OrderKind(enum.Enum):
    ENTRY = "ENTRY"
    EXIT = "EXIT"


def is_terminal_status(status: str) -> bool:
    """Lighter order statuses after which no further fill can happen."""
    return status == "filled" or status.startswith("canceled")


@dataclass(frozen=True, slots=True)
class OrderUpdate:
    """One order object from the authenticated order stream or REST."""

    client_order_index: int
    order_index: int
    market_id: int
    is_ask: bool
    status: str
    filled: int  # cumulative, size units
    filled_quote_q: int  # cumulative, quote units
    remaining: int
    reduce_only: bool


@dataclass(frozen=True, slots=True)
class TradeFill:
    """One of our fills from the authenticated trade stream."""

    trade_id: int
    client_order_index: int
    market_id: int
    size: int
    price: int
    is_taker: bool
    fee_tick: int


@dataclass(frozen=True, slots=True)
class ExchangePosition:
    """Authoritative BTC position as reported by the exchange."""

    signed_size: int  # size units, positive long / negative short
    avg_entry_price: int  # price units
    open_orders: int
    pending_orders: int
    imf: int | None  # initial margin fraction, 1/10_000
    margin_mode: int | None
    seen_ns: int


@dataclass(slots=True)
class ActiveOrder:
    """A single order sent by the bot and everything learned about it since."""

    client_order_index: int
    kind: OrderKind
    is_ask: bool
    size: int
    limit_price: int
    reduce_only: bool
    market_order: bool  # True: MARKET+IOC, False: LIMIT+IOC
    reason: str
    created_ns: int
    emergency: bool = False
    tx_hash: str = ""
    signed_ns: int = 0
    sent_ns: int = 0
    ack_ns: int = 0
    acked: bool = False
    first_fill_ns: int = 0
    done_ns: int = 0
    status: str = "local"
    terminal: bool = False
    order_index: int = 0
    filled: int = 0  # effective cumulative fill already applied to the position
    filled_quote_q: int = 0
    applied: int = 0  # part of ``filled`` already booked into the position
    applied_quote_q: int = 0
    _ou_filled: int = 0
    _ou_quote_q: int = 0
    _tr_filled: int = 0
    _tr_quote_q: int = 0
    _trade_ids: set[int] = field(default_factory=set)

    def apply_order_update(self, update: OrderUpdate, now_ns: int) -> tuple[int, int]:
        """Merge a cumulative order update. Returns the new ``(base, quote)`` fill delta."""
        if update.filled > self._ou_filled:
            self._ou_filled = update.filled
            self._ou_quote_q = update.filled_quote_q
        if update.order_index:
            self.order_index = update.order_index
        if not self.terminal:
            self.status = update.status
            if is_terminal_status(update.status):
                self.terminal = True
                self.done_ns = now_ns
        return self._advance(now_ns)

    def apply_trade(self, trade: TradeFill, now_ns: int) -> tuple[int, int]:
        """Merge one fill (idempotent per trade id). Returns the new ``(base, quote)`` delta."""
        if trade.trade_id in self._trade_ids:
            return 0, 0
        self._trade_ids.add(trade.trade_id)
        self._tr_filled += trade.size
        self._tr_quote_q += trade.size * trade.price
        return self._advance(now_ns)

    def mark_terminal(self, status: str, now_ns: int) -> None:
        """Close the order locally (definitive rejection or reconciliation result)."""
        if not self.terminal:
            self.terminal = True
            self.status = status
            self.done_ns = now_ns

    def _advance(self, now_ns: int) -> tuple[int, int]:
        # Prefer the trade feed when both agree on size: its notional is exact.
        if self._tr_filled >= self._ou_filled:
            effective, effective_q = self._tr_filled, self._tr_quote_q
        else:
            effective, effective_q = self._ou_filled, self._ou_quote_q
        d_base = effective - self.filled
        d_quote = effective_q - self.filled_quote_q
        if d_base < 0 or (d_base == 0 and d_quote == 0):
            return 0, 0
        self.filled = effective
        self.filled_quote_q = effective_q
        if d_base > 0 and self.first_fill_ns == 0:
            self.first_fill_ns = now_ns
        return d_base, d_quote

    @property
    def avg_price(self) -> float:
        return self.filled_quote_q / self.filled if self.filled else 0.0


@dataclass(slots=True)
class Position:
    """The bot's single BTC position, built from confirmed fills only."""

    side: int
    opened_ns: int
    size: int = 0  # remaining, size units
    cost_q: int = 0  # cost basis of the remaining size
    fee_q: int = 0  # entry fees attributable to the remaining size
    entry_size: int = 0
    entry_value_q: int = 0
    entry_fee_q: int = 0
    exit_size: int = 0
    exit_value_q: int = 0
    exit_fee_q: int = 0
    closed_cost_q: int = 0  # cost basis of everything already closed
    adopted: bool = False  # discovered on the exchange rather than opened in this run
    mfe_q: int = 0  # maximum favourable excursion (best executable net P&L seen)
    mae_q: int = 0  # maximum adverse excursion (worst executable net P&L seen)

    def add_entry(self, d_base: int, d_quote: int, fee: int) -> None:
        self.size += d_base
        self.cost_q += d_quote
        self.fee_q += fee
        self.entry_size += d_base
        self.entry_value_q += d_quote
        self.entry_fee_q += fee

    def add_exit(self, d_base: int, d_quote: int, fee: int) -> None:
        """Apply an exit fill. Never drives the remaining size below zero."""
        closed = d_base if d_base < self.size else self.size
        if closed > 0:
            if closed == self.size:
                cost_part, fee_part = self.cost_q, self.fee_q
            else:
                cost_part = self.cost_q * closed // self.size
                fee_part = self.fee_q * closed // self.size
            self.size -= closed
            self.cost_q -= cost_part
            self.fee_q -= fee_part
            self.closed_cost_q += cost_part
        self.exit_size += d_base
        self.exit_value_q += d_quote
        self.exit_fee_q += fee

    def observe(self, net_pnl_q: int) -> None:
        """Track excursions from an executable close estimate."""
        if net_pnl_q > self.mfe_q:
            self.mfe_q = net_pnl_q
        if net_pnl_q < self.mae_q:
            self.mae_q = net_pnl_q

    @property
    def avg_entry(self) -> float:
        return self.cost_q / self.size if self.size else 0.0

    @property
    def signed_size(self) -> int:
        return self.side * self.size


@dataclass(slots=True)
class TradeContext:
    """Timestamps and signal context for the trade currently in flight (journal + latency)."""

    side: int
    trade_id: str = field(default_factory=lambda: uuid.uuid4().hex)
    signal_score: float = 0.0
    signal_components: dict[str, float] = field(default_factory=dict)
    wall_anchor_ns: int = field(default_factory=time.time_ns)
    mono_anchor_ns: int = field(default_factory=time.monotonic_ns)
    signal_ns: int = 0
    decision_ns: int = 0
    entry_signed_ns: int = 0
    entry_sent_ns: int = 0
    entry_ack_ns: int = 0
    first_fill_ns: int = 0
    full_fill_ns: int = 0
    profit_detected_ns: int = 0
    exit_decision_ns: int = 0
    exit_signed_ns: int = 0
    exit_sent_ns: int = 0
    exit_ack_ns: int = 0
    flat_ns: int = 0
    exit_reason: str = ""
    entry_ref_price: int = 0  # best price when the entry was decided
    exit_ref_price: int = 0  # best price when the (first) exit was decided
    expected_net_q: int = 0  # estimated net P&L at exit decision
    estimated_slippage_q: int = 0

    def wall_ns(self, mono_ns: int) -> int:
        """Convert a monotonic timestamp of this trade to wall-clock nanoseconds."""
        return self.wall_anchor_ns + (mono_ns - self.mono_anchor_ns) if mono_ns else 0
